version: '3'
services:
  #DB---------------------------------------------------------------------------------------------------------------------

  generator-database:
    container_name: generator-database
    image: postgres:10.0-alpine
    environment:
      - POSTGRES_DB=generator
      - POSTGRES_USER=generator
      - POSTGRES_PASSWORD=generator
      - TZ=GMT-3
    ports:
      - "5569:5432"
    volumes:
      - ${HOME}/db-data/generator:/var/lib/postgresql/data
      - ${HOME}/docker/dumps:/var/dumps


